name: CI/CD Pipeline

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18.x"

            - name: Install Dependencies
              run: npm install

            - name: Build
              run: npm run build


    test:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18.x"

            - name: Install Dependencies
              run: npm install

            - name: Run Tests
              run: npm test

    vercel-deploy:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18.x"

            - name: Install Dependencies
              run: npm install

            - name: Deploy to Vercel
              env:
                  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
              run: |
                  npm install -g vercel
                  vercel --prod --token $VERCEL_TOKEN --yes

    docker-push-dockerHub:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v5
              with:
                context: .
                file: Dockerfile.prod
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/portfolio:latest
                build-args: |
                  TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}
                  TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}

    railway-deploy:
        runs-on: ubuntu-latest
        needs: docker-push-dockerHub
        steps:
            - uses: actions/checkout@v3

            - name: Install Railway CLI
              run: npm i -g @railway/cli

            - name: Deploy to Railway
              env:
                RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
              run: |
                railway up --dockerfile Dockerfile.prod